! (C) Copyright 2016- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation nor
! does it submit to any jurisdiction.

module pluto_module_allocate_deallocate
! This is a separate module which is used by pluto_module to implement the allocation and deallocation procedures
! which use the C memory resource interface.

use, intrinsic :: iso_fortran_env, only : int32, int64, real32, real64
use pluto_module_memory_resource, only : pluto_memory_resource, pluto_get_label, pluto_set_label
implicit none
private

#:set ranks  = [1,2,3,4,5]
#:set dim    = ['',':',':,:',':,:,:',':,:,:,:',':,:,:,:,:']
#:set dtypes = ['int32','int64','real32','real64']
#:set ftype  = dict(zip(dtypes, ['integer(int32)', 'integer(int64)', 'real(real32)', 'real(real64)']))

public :: pluto_allocate, pluto_deallocate

interface pluto_allocate
#:for rank in ranks
#:for dtype in dtypes
#:set array = dtype + '_r' + str(rank)
    module procedure pluto_allocate_${array}$_bounds
    module procedure pluto_allocate_${array}$_shape
    module procedure pluto_allocate_label_${array}$_bounds
    module procedure pluto_allocate_label_${array}$_shape
#:endfor
#:endfor
end interface

interface pluto_deallocate
#:for rank in ranks
#:for dtype in dtypes
#:set array = dtype + '_r' + str(rank)
    module procedure pluto_deallocate_${array}$
    module procedure pluto_deallocate_label_${array}$
#:endfor
#:endfor
end interface

interface
#:for rank in ranks
#:for dtype in dtypes
#:set array = dtype + '_r' + str(rank)
    module subroutine pluto_allocate_${array}$_bounds(array, lbounds, ubounds, resource)
        ${ftype[dtype]}$, pointer, intent(inout) :: array(${dim[rank]}$)
        integer(int32), intent(in) :: lbounds(${rank}$)
        integer(int32), intent(in) :: ubounds(${rank}$)
        type(pluto_memory_resource), intent(in) :: resource
    end subroutine

    module subroutine pluto_allocate_${array}$_shape(array, shape, resource)
        ${ftype[dtype]}$, pointer, intent(inout) :: array(${dim[rank]}$)
        integer(int32), intent(in) :: shape(${rank}$)
        type(pluto_memory_resource), intent(in) :: resource
    end subroutine

    module subroutine pluto_allocate_label_${array}$_bounds(label, array, lbounds, ubounds, resource)
        character(len=*), intent(in) :: label
        ${ftype[dtype]}$, pointer, intent(inout) :: array(${dim[rank]}$)
        integer(int32), intent(in) :: lbounds(${rank}$)
        integer(int32), intent(in) :: ubounds(${rank}$)
        type(pluto_memory_resource), intent(in) :: resource
    end subroutine

    module subroutine pluto_allocate_label_${array}$_shape(label, array, shape, resource)
        character(len=*), intent(in) :: label
        ${ftype[dtype]}$, pointer, intent(inout) :: array(${dim[rank]}$)
        integer(int32), intent(in) :: shape(${rank}$)
        type(pluto_memory_resource), intent(in) :: resource
    end subroutine

    module subroutine pluto_deallocate_${array}$(array, resource)
        ${ftype[dtype]}$, pointer, intent(inout) :: array(${dim[rank]}$)
        type(pluto_memory_resource), intent(in) :: resource
    end subroutine

    module subroutine pluto_deallocate_label_${array}$(label, array, resource)
        character(len=*), intent(in) :: label
        ${ftype[dtype]}$, pointer, intent(inout) :: array(${dim[rank]}$)
        type(pluto_memory_resource), intent(in) :: resource
    end subroutine
#:endfor
#:endfor
end interface

end module
