! (C) Copyright 2016- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation nor
! does it submit to any jurisdiction.

#:include "pluto_defs.fypp"

module pluto_module_allocator

use, intrinsic :: iso_fortran_env, only : int32, int64, real32, real64
use pluto_module_memory_resource, only : pluto_memory_resource

implicit none
private

public :: pluto_allocator
public :: pluto_make_allocator

type pluto_allocator
    type(pluto_memory_resource) :: memory_resource
contains

    $:generic_procedure('allocate', [ &
        'pluto_allocator_allocate_array_shape', &
        'pluto_allocator_allocate_array_bounds', &
        'pluto_allocator_allocate_label_array_shape', &
        'pluto_allocator_allocate_label_array_bounds'])

    $:generic_procedure('deallocate', [ &
        'pluto_allocator_deallocate_array', &
        'pluto_allocator_deallocate_label_array'])

    procedure, private :: pluto_allocator_init_type
    procedure, private :: pluto_allocator_init_name
    generic, public :: init => pluto_allocator_init_type, pluto_allocator_init_name

end type

interface pluto_make_allocator
    module procedure pluto_make_allocator_type
    module procedure pluto_make_allocator_name
end interface

interface

module subroutine pluto_allocator_init_type(this, resource)
    class(pluto_allocator) :: this
    type(pluto_memory_resource), intent(in) :: resource
end subroutine

module subroutine pluto_allocator_init_name(this, resource)
    class(pluto_allocator) :: this
    character(len=*), target, intent(in) :: resource
end subroutine

module function pluto_make_allocator_type(resource) result(allocator)
    type(pluto_allocator) :: allocator
    type(pluto_memory_resource) :: resource
end function

module function pluto_make_allocator_name(resource) result(allocator)
    type(pluto_allocator) :: allocator
    character(len=*), target, intent(in) :: resource
end function
end interface

interface
#:for rank in ranks
#:for dtype in dtypes
#:set array = dtype + '_r' + str(rank)
module subroutine pluto_allocator_allocate_${array}$_bounds(this, array, lbounds, ubounds)
    class(pluto_allocator) :: this
    ${ftype[dtype]}$, pointer, intent(inout) :: array(${dim[rank]}$)
    integer(int32), intent(in) :: lbounds(${rank}$), ubounds(${rank}$)
end subroutine
module subroutine pluto_allocator_allocate_${array}$_shape(this, array, shape)
    class(pluto_allocator) :: this
    ${ftype[dtype]}$, pointer, intent(inout) :: array(${dim[rank]}$)
    integer(int32), intent(in) :: shape(${rank}$)
end subroutine
module subroutine pluto_allocator_allocate_label_${array}$_bounds(this, label, array, lbounds, ubounds)
    class(pluto_allocator) :: this
    character(len=*), intent(in) :: label
    ${ftype[dtype]}$, pointer, intent(inout) :: array(${dim[rank]}$)
    integer(int32), intent(in) :: lbounds(${rank}$), ubounds(${rank}$)
end subroutine
module subroutine pluto_allocator_allocate_label_${array}$_shape(this, label, array, shape)
    class(pluto_allocator) :: this
    character(len=*), intent(in) :: label
    ${ftype[dtype]}$, pointer, intent(inout) :: array(${dim[rank]}$)
    integer(int32), intent(in) :: shape(${rank}$)
end subroutine
#:endfor
#:endfor

#:for rank in ranks
#:for dtype in dtypes
#:set array = dtype + '_r' + str(rank)
module subroutine pluto_allocator_deallocate_${array}$(this, array)
    class(pluto_allocator) :: this
    ${ftype[dtype]}$, pointer, intent(inout) :: array(${dim[rank]}$)
end subroutine
module subroutine pluto_allocator_deallocate_label_${array}$(this, label, array)
    class(pluto_allocator) :: this
    character(len=*), intent(in) :: label
    ${ftype[dtype]}$, pointer, intent(inout) :: array(${dim[rank]}$)
end subroutine
#:endfor
#:endfor

end interface
end module
