! (C) Copyright 2016- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation nor
! does it submit to any jurisdiction.

module pluto_module_allocator

use, intrinsic :: iso_fortran_env, only : int32, int64, real32, real64
use pluto_module_memory_resource, only : pluto_memory_resource

implicit none
private

#:set ranks  = [1,2,3,4,5]
#:set dim    = ['',':',':,:',':,:,:',':,:,:,:',':,:,:,:,:']
#:set dtypes = ['int32','int64','real32','real64']
#:set ftype  = dict(zip(dtypes, ['integer(int32)', 'integer(int64)', 'real(real32)', 'real(real64)']))

public :: pluto_allocator
public :: pluto_make_allocator

type pluto_allocator
    type(pluto_memory_resource) :: memory_resource
contains

#:for rank in ranks
#:for dtype in dtypes
#:set array = dtype + '_r' + str(rank)
    procedure, private :: pluto_allocator_allocate_${array}$_shape
    procedure, private :: pluto_allocator_allocate_${array}$_bounds
    procedure, private :: pluto_allocator_allocate_label_${array}$_shape
    procedure, private :: pluto_allocator_allocate_label_${array}$_bounds
#:endfor
#:endfor

#:for rank in ranks
#:for dtype in dtypes
#:set array = dtype + '_r' + str(rank)
    generic, public :: allocate => pluto_allocator_allocate_${array}$_shape
    generic, public :: allocate => pluto_allocator_allocate_${array}$_bounds
    generic, public :: allocate => pluto_allocator_allocate_label_${array}$_shape
    generic, public :: allocate => pluto_allocator_allocate_label_${array}$_bounds
#:endfor
#:endfor

#:for rank in ranks
#:for dtype in dtypes
#:set array = dtype + '_r' + str(rank)
    procedure, private :: pluto_allocator_deallocate_${array}$
    procedure, private :: pluto_allocator_deallocate_label_${array}$
#:endfor
#:endfor

#:for rank in ranks
#:for dtype in dtypes
#:set array = dtype + '_r' + str(rank)
    generic, public :: deallocate => pluto_allocator_deallocate_${array}$
    generic, public :: deallocate => pluto_allocator_deallocate_label_${array}$
#:endfor
#:endfor
end type

interface pluto_make_allocator
    module procedure pluto_make_allocator_type
    module procedure pluto_make_allocator_name
end interface

interface
module function pluto_make_allocator_type(resource) result(allocator)
    type(pluto_allocator) :: allocator
    type(pluto_memory_resource) :: resource
end function

module function pluto_make_allocator_name(resource) result(allocator)
    type(pluto_allocator) :: allocator
    character(len=*), target, intent(in) :: resource
end function
end interface

interface
#:for rank in ranks
#:for dtype in dtypes
#:set array = dtype + '_r' + str(rank)
module subroutine pluto_allocator_allocate_${array}$_bounds(this, array, lbounds, ubounds)
    class(pluto_allocator) :: this
    ${ftype[dtype]}$, pointer, intent(inout) :: array(${dim[rank]}$)
    integer(int32), intent(in) :: lbounds(${rank}$), ubounds(${rank}$)
end subroutine
module subroutine pluto_allocator_allocate_${array}$_shape(this, array, shape)
    class(pluto_allocator) :: this
    ${ftype[dtype]}$, pointer, intent(inout) :: array(${dim[rank]}$)
    integer(int32), intent(in) :: shape(${rank}$)
end subroutine
module subroutine pluto_allocator_allocate_label_${array}$_bounds(this, label, array, lbounds, ubounds)
    class(pluto_allocator) :: this
    character(len=*), intent(in) :: label
    ${ftype[dtype]}$, pointer, intent(inout) :: array(${dim[rank]}$)
    integer(int32), intent(in) :: lbounds(${rank}$), ubounds(${rank}$)
end subroutine
module subroutine pluto_allocator_allocate_label_${array}$_shape(this, label, array, shape)
    class(pluto_allocator) :: this
    character(len=*), intent(in) :: label
    ${ftype[dtype]}$, pointer, intent(inout) :: array(${dim[rank]}$)
    integer(int32), intent(in) :: shape(${rank}$)
end subroutine
#:endfor
#:endfor

#:for rank in ranks
#:for dtype in dtypes
#:set array = dtype + '_r' + str(rank)
module subroutine pluto_allocator_deallocate_${array}$(this, array)
    class(pluto_allocator) :: this
    ${ftype[dtype]}$, pointer, intent(inout) :: array(${dim[rank]}$)
end subroutine
module subroutine pluto_allocator_deallocate_label_${array}$(this, label, array)
    class(pluto_allocator) :: this
    character(len=*), intent(in) :: label
    ${ftype[dtype]}$, pointer, intent(inout) :: array(${dim[rank]}$)
end subroutine
#:endfor
#:endfor

end interface
end module
