! (C) Copyright 2022- ECMWF.
! (C) Copyright 2022- Meteo-France.
! (C) Copyright 2023- NVIDIA
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

PROGRAM INIT_WRAPPER_NON_CONTIGUOUS_GPU
  ! TEST IF WRAPPER WORKS WITH NON CONTIGUOUS ARRAY
  USE ATLAS_MODULE, ONLY : ATLAS_LIBRARY
  USE FIELD_MODULE
  USE PARKIND1
  USE FIELD_FACTORY_MODULE
  use iso_c_binding

  IMPLICIT NONE
  REAL(KIND=JPRB), ALLOCATABLE, TARGET :: D1(:,:,:,:,:), D2(:,:,:,:,:)
  CLASS(FIELD_2RB), POINTER :: W2 => NULL()
  REAL(KIND=JPRB), POINTER :: W2PTR(:,:)
  CLASS(FIELD_3RB), POINTER :: W3 => NULL()
  REAL(KIND=JPRB), POINTER :: W3PTR(:,:,:)
  CLASS(FIELD_4RB), POINTER :: W4 => NULL()
  REAL(KIND=JPRB), POINTER :: W4PTR(:,:,:,:)
  integer(kind=8) :: ptr

  CALL ATLAS_LIBRARY%INITIALISE()

  ALLOCATE(D1(7, 9, 11, 13, 15))
  ALLOCATE(D2(7, 9, 11, 13, 15))
  D1 = 0
  D2 = 0

  PRINT *, "begin 1 (should call FIELD_4RB_COPY_2D_DIM1_4_CONTIGUOUS)"
  CALL FIELD_NEW(W4, DATA=D1(1:1,:,:,:,3))
  CALL W4%GET_HOST_DATA_RDWR(W4PTR)
  W4PTR=42
  CALL W4%GET_DEVICE_DATA_RDWR(W4PTR)

  write(0,*) "DEVICE_ALLOCATED", W4%F%DEVICE_ALLOCATED()

  !$ACC KERNELS DEFAULT(PRESENT)
  W4PTR(:,:,:,:)=92
  !$ACC END KERNELS
  IF (W4%F%DEVICE_ALLOCATED()) THEN
    D1 = -1
    D2 = -1
  ENDIF
  D2(1:1,:,:,:,3)=92
  CALL W4%GET_HOST_DATA_RDONLY(W4PTR)
  CALL FIELD_DELETE(W4)
  IF (ANY(D1/=D2)) ERROR STOP
  PRINT *, "end 1"
  PRINT *, ""

  PRINT *, "begin 2 (should call FIELD_4RB_COPY_2D_DIM1_3_CONTIGUOUS)"
  ! Should call DIM1_3
  CALL FIELD_NEW(W3, DATA=D1(:,2,:,:,3))
  CALL W3%GET_HOST_DATA_RDWR(W3PTR)
  W3PTR=51
  CALL W3%GET_DEVICE_DATA_RDWR(W3PTR)
  !$ACC KERNELS DEFAULT(PRESENT)
  W3PTR(:,:,:)=61
  !$ACC END KERNELS
  IF (W3%F%DEVICE_ALLOCATED()) THEN
    D1 = -1
    D2 = -1
  ENDIF
  D2(:,2,:,:,3)=61
  CALL FIELD_DELETE(W3)
  IF (ANY(D1/=D2)) ERROR STOP
  PRINT *, "end 2"
  PRINT *, ""

  PRINT *, "begin 3 (should call FIELD_4RB_COPY_2D_DIM3_4_CONTIGUOUS)"
  CALL FIELD_NEW(W4, DATA=D1(:,:,4:8,:,3))
  CALL W4%GET_DEVICE_DATA_RDWR(W4PTR)
  !$ACC KERNELS DEFAULT(PRESENT)
  W4PTR(:,:,:,:)=31
  !$ACC END KERNELS
  IF (W4%F%DEVICE_ALLOCATED()) THEN
    D1 = -1
    D2 = -1
  ENDIF
  D2(:,:,4:8,:,3)=31
  CALL FIELD_DELETE(W4)
  IF (ANY(D1/=D2)) ERROR STOP
  PRINT *, "end 3"
  PRINT *, ""

  PRINT *, "begin 4 (should call FIELD_3RB_COPY_2D_DIM1_2_CONTIGUOUS)"
#if 0
  CALL FIELD_NEW(W3, DATA=D1(:,2,4:8,3:5,3))
  CALL W3%GET_DEVICE_DATA_RDWR(W3PTR)
  !$ACC KERNELS DEFAULT(PRESENT)
  W3PTR(:,:,:)=91
  !$ACC END KERNELS
  IF (W3%F%DEVICE_ALLOCATED()) THEN
    D1 = -1
    D2 = -1
  ENDIF
  D2(:,2,4:8,3:5,3)=91
  CALL FIELD_DELETE(W3)
  IF (ANY(D1/=D2)) ERROR STOP
#else
  PRINT *, "WARNING: Array is discontiguous in multiple dimensions, not supported with Atlas; skipping test!"
#endif
  PRINT *, "end 4"
  PRINT *, ""

  PRINT *, "begin 5 (should call FIELD_2RB_COPY_2D_DIM1_2_CONTIGUOUS)"
  CALL FIELD_NEW(W2, DATA=D1(:,2,4:8,8,3))
  CALL W2%GET_DEVICE_DATA_RDWR(W2PTR)
  !$ACC KERNELS DEFAULT(PRESENT)
  W2PTR(:,:)=12.1
  !$ACC END KERNELS
  IF (W2%F%DEVICE_ALLOCATED()) THEN
    D1 = -1
    D2 = -1
  ENDIF
  D2(:,2,4:8,8,3)=12.1
  CALL FIELD_DELETE(W2)
  IF (ANY(D1/=D2)) ERROR STOP
  PRINT *, "end 5"
  PRINT *, ""

  PRINT *, "begin 6 (should call FIELD_4RB_COPY_2D_DIM2_4_CONTIGUOUS)"
  CALL FIELD_NEW(W4, DATA=D1(:,:,4,:,:))
  CALL W4%GET_DEVICE_DATA_RDWR(W4PTR)
  !$ACC KERNELS DEFAULT(PRESENT)
  W4PTR(:,:,:,:)=22.1
  !$ACC END KERNELS
  IF (W4%F%DEVICE_ALLOCATED()) THEN
    D1 = -1
    D2 = -1
  ENDIF
  D2(:,:,4,:,:)=22.1
  CALL FIELD_DELETE(W4)
  IF (ANY(D1/=D2)) ERROR STOP
  PRINT *, "end 6"
  PRINT *, ""


  CALL ATLAS_LIBRARY%FINALISE()

END PROGRAM INIT_WRAPPER_NON_CONTIGUOUS_GPU