! (C) Copyright 2022- ECMWF.
! (C) Copyright 2022- Meteo-France.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

PROGRAM TEST_OWNER_LASTDIM

USE ATLAS_MODULE, ONLY : ATLAS_LIBRARY
USE FIELD_MODULE
USE FIELD_FACTORY_MODULE
USE FIELD_ABORT_MODULE
USE PARKIND1

IMPLICIT NONE

CLASS (FIELD_3RB), POINTER :: YLF => NULL()

REAL (KIND=JPRB), POINTER :: ZDATA (:,:,:)
REAL (KIND=JPRB), POINTER :: ZVIEW (:,:)

REAL (KIND=JPRB), ALLOCATABLE :: ZDATA0 (:,:,:)

INTEGER :: JBLK

CALL ATLAS_LIBRARY%INITIALISE()

CALL FIELD_NEW (YLF, LBOUNDS=[10,1,3], UBOUNDS=[21,11,10], PERSISTENT=.TRUE.)

CALL YLF%GET_HOST_DATA_RDWR(ZDATA)

PRINT *, " LBOUND (ZDATA) = ", LBOUND (ZDATA)
PRINT *, " UBOUND (ZDATA) = ", UBOUND (ZDATA)

DO JBLK = LBOUND (ZDATA, 3), UBOUND (ZDATA, 3)
  ZDATA (:,:,JBLK) = REAL (JBLK, JPRB)
ENDDO

DO JBLK = LBOUND (ZDATA, 3), UBOUND (ZDATA, 3)
  ZVIEW => YLF%GET_VIEW (BLOCK_INDEX=JBLK)
  IF (ANY (ZVIEW /= REAL (JBLK, JPRB))) CALL FIELD_ABORT ('UNEXPECTED VALUES')
ENDDO

CALL FIELD_DELETE (YLF)

ALLOCATE (ZDATA0 (10:21, 1:11, 3:10))

CALL FIELD_NEW (YLF, LBOUNDS=[10,1,3], DATA=ZDATA0)

CALL YLF%GET_HOST_DATA_RDWR(ZDATA)

PRINT *, " LBOUND (ZDATA) = ", LBOUND (ZDATA)
PRINT *, " UBOUND (ZDATA) = ", UBOUND (ZDATA)

DO JBLK = LBOUND (ZDATA, 3), UBOUND (ZDATA, 3)
  ZDATA (:,:,JBLK) = REAL (JBLK, JPRB)
ENDDO

DO JBLK = LBOUND (ZDATA, 3), UBOUND (ZDATA, 3)
  ZVIEW => YLF%GET_VIEW (BLOCK_INDEX=JBLK)
  IF (ANY (ZVIEW /= REAL (JBLK, JPRB))) CALL FIELD_ABORT ('UNEXPECTED VALUES')
ENDDO

CALL FIELD_DELETE (YLF)

CALL ATLAS_LIBRARY%FINALISE()

END PROGRAM TEST_OWNER_LASTDIM

