name: Check VERSION file

on:
  push:
    branches:
      - "release/**"
      - "hotfix/**"

jobs:
  check_version:
    uses: ecmwf-actions/reusable-workflows/.github/workflows/check-release-version.yml@v2
