name: Notify new issue

on:
  issues:
    types:
      - "opened"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify new issue
        uses: ecmwf-actions/notify-teams-issue@v1
        with:
          incoming_webhook: ${{ secrets.MS_TEAMS_INCOMING_WEBHOOK }}
