name: reusable-ci-hpc

on:
  workflow_call:
    inputs:
      atlas:
        required: false
        type: string
      eckit:
        required: false
        type: string
jobs:
  ci-hpc:
    name: ci-hpc
    uses: ecmwf-actions/reusable-workflows/.github/workflows/ci-hpc.yml@v2
    with:
      name-prefix: atlas-
      build-inputs: |
        --package: ${{ inputs.atlas || 'ecmwf/atlas@develop' }}
        --modules: |
          ecbuild
          ninja
        --modules-package: |
          atlas:fftw,eigen
        --dependencies: |
          ${{ inputs.eckit || 'ecmwf/eckit@develop' }}
        --parallel: 64
    secrets: inherit
